stages:
  - lint
  - build

Debug APK:
  tags:
    - docker
  except:
    - master
  stage: build
  image: circleci/android:api-27-alpha
  script:
    - ./minify_json.sh
    - ./gradlew assembleDebugMinified
  artifacts:
    name: "apk-debug-$CI_COMMIT_SHA"
    paths:
      - ./bunnies/build/outputs/apk/debugMinified/*.apk
      - ./bunnies/build/outputs/mapping/debugMinified/mapping.txt

Release APK:
  tags:
    - docker
  only:
    - master
  stage: build
  image: circleci/android:api-27-alpha
  script:
    - ./minify_json.sh
    - ./gradlew assembleRelease
  artifacts:
    name: "apk-release-$CI_COMMIT_SHA"
    paths:
      - ./bunnies/build/outputs/apk/release/*.apk
      - ./bunnies/build/outputs/mapping/release/mapping.txt

Android Lint:
  tags:
    - docker
  stage: lint
  image: circleci/android:api-27-alpha
  script:
    - ./minify_json.sh
    - ./gradlew lint
  artifacts:
    name: "lint-$CI_COMMIT_SHA"
    paths:
      - ./bunnies/build/reports/lint-results.html
      - ./bunnies/build/reports/lint-results.xml
