stages:
  - Build

Debug APK:
  tags:
    - docker
  except:
    - master
  stage: Build
  environment:
    name: "$CI_COMMIT_REF_NAME"
    url: "$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/file/bunnies/build/outputs/apk/debugMinified/bunnies-debugMinified.apk"
  image: michiganlabs/android:api-27-alpha
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - build/
      - bunnies/build/
  script:
    - python ./database/dbseed.py
    - ./gradlew assembleDebugMinified
  artifacts:
    name: "bunnypedia-debug-$CI_COMMIT_SHA"
    paths:
      - ./bunnies/build/outputs/apk/debugMinified/*.apk
      - ./bunnies/build/outputs/mapping/debugMinified/mapping.txt
    expire_in: 1 month

Release APK:
  tags:
    - docker
  only:
    - master
  stage: Build
  environment:
    name: Play Store
    url: "https://play.google.com/store/apps/details?id=com.fueledbycaffeine.bunnypedia"
  image: michiganlabs/android:api-27-alpha
  script:
    - python ./database/dbseed.py
    - ./gradlew assembleRelease
  artifacts:
    name: "bunnypedia-release-$CI_COMMIT_SHA"
    paths:
      - ./bunnies/build/outputs/apk/release/*.apk
      - ./bunnies/build/outputs/mapping/release/mapping.txt

Android Lint:
  tags:
    - docker
  stage: Build
  allow_failure: true
  image: michiganlabs/android:api-27-alpha
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - build/
      - bunnies/build/
  script:
    - python ./database/dbseed.py
    - ./gradlew lint
  artifacts:
    name: "bunnypedia-lint-$CI_COMMIT_SHA"
    paths:
      - ./bunnies/build/reports/lint-results.html
      - ./bunnies/build/reports/lint-results.xml
    expire_in: 1 month
